name: Fluxility
favicon: null
layout_spectrum: 0.49062
typography_spectrum: 0.73152
title: Fluxility
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#455dfe'
    - '#92f6f5'
    - '#282828'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
