name: Fluxility
favicon: null
layout_spectrum: 0.2537028209771961
typography_spectrum: 0.9847624122630805
title: Fluxility
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5257103976327926
  lightness: 0.31394160771742463
  saturation: 0.6685222012456506
  rhythmicContrast: 0.9181542920414358
purpose: []
